sudo: required
dist: trusty

os: linux

arch:
  - amd64
  - x86
  - arm64

language: c
compiler:
  - gcc
  - clang

cache:
  directories:
  - download-cache

env:
  global:
    - JOBS=3
    - SH=bash
    - NGX_BUILD_JOBS=$JOBS
    - LUAJIT_PREFIX=/tmp/luajit21
    - LUAJIT_LIB=$LUAJIT_PREFIX/lib
    - LUAJIT_INC=$LUAJIT_PREFIX/include/luajit-2.1
    - LUA_INCLUDE_DIR=$LUAJIT_INC
    - OPENSSL_PREFIX=/tmp/ssl
    - OPENSSL_LIB=$OPENSSL_PREFIX/lib
    - OPENSSL_INC=$OPENSSL_PREFIX/include
    - LD_LIBRARY_PATH=$LUAJIT_LIB:$LD_LIBRARY_PATH
    - TEST_NGINX_SLEEP=0.005
    - TEST_NGINX_RANDOMIZE=1
    - LUACHECK_VER=0.21.1
  matrix:
    - NGINX_VERSION=1.15.8 OPENSSL_VER=1.0.2t
    - NGINX_VERSION=1.15.8 OPENSSL_VER=1.1.0l
    - NGINX_VERSION=1.15.8 OPENSSL_VER=1.1.1d

# skip some combinations
matrix:
  exclude:
    - arch: arm
      compiler: clang
    - arch: arm64
      compiler: clang
    # only test amd64 for minor version
    - arch: i386
      env: NGINX_VERSION=1.15.8 OPENSSL_VER=1.1.0l
    - arch: arm
      env: NGINX_VERSION=1.15.8 OPENSSL_VER=1.1.0l
    - arch: arm64
      env: NGINX_VERSION=1.15.8 OPENSSL_VER=1.1.0l

install:
  - export NGX_BUILD_CC=$CC
  - export PATH=$PWD/work/nginx/sbin:$PWD/nginx-devel-utils:$PATH
  - sudo apt-get install -qq -y cpanminus axel
  - sudo cpanm --notest Test::Nginx > build.log 2>&1 || (cat build.log && exit 1)
  - git clone https://github.com/openresty/openresty.git ../openresty
  - git clone https://github.com/openresty/nginx-devel-utils.git
  - git clone https://github.com/simpl/ngx_devel_kit.git ../ndk-nginx-module
  - git clone https://github.com/openresty/lua-nginx-module.git ../lua-nginx-module
  - git clone https://github.com/openresty/lua-resty-core.git ../lua-resty-core
  - git clone https://github.com/openresty/no-pool-nginx.git ../no-pool-nginx
  - git clone https://github.com/openresty/lua-resty-lrucache.git ../lua-resty-lrucache
  # luajit
  - git clone -b v2.1-agentzh https://github.com/openresty/luajit2.git
  - pushd luajit2/
  - make -j$JOBS CCDEBUG=-g Q= PREFIX=$LUAJIT_PREFIX CC=$CC XCFLAGS='-DLUA_USE_APICHECK -DLUA_USE_ASSERT' > build.log 2>&1 || (cat build.log && exit 1)
  - make install PREFIX=$LUAJIT_PREFIX > build.log 2>&1 || (cat build.log && exit 1)
  - popd
  - mkdir -p download-cache
  # openssl
  - if [ ! -f download-cache/openssl-$OPENSSL_VER.tar.gz ]; then wget -O download-cache/openssl-$OPENSSL_VER.tar.gz https://www.openssl.org/source/openssl-$OPENSSL_VER.tar.gz; fi
  - tar zxf download-cache/openssl-$OPENSSL_VER.tar.gz
  - pushd openssl-$OPENSSL_VER/
  - ./config shared --prefix=$OPENSSL_PREFIX -DPURIFY > build.log 2>&1 || (cat build.log && exit 1)
  - make -j$JOBS > build.log 2>&1 || (cat build.log && exit 1)
  - sudo make PATH=$PATH install_sw > build.log 2>&1 || (cat build.log && exit 1)
  - popd
  # nginx
  - ngx-build $NGINX_VERSION --add-module=../ndk-nginx-module --add-module=../lua-nginx-module --with-http_ssl_module --with-cc-opt="-I$OPENSSL_INC" --with-ld-opt="-L$OPENSSL_LIB -Wl,-rpath,$OPENSSL_LIB" --with-debug > build.log 2>&1 || (cat build.log && exit 1)
  - nginx -V
  - ldd `which nginx`|grep -E 'luajit|ssl|pcre'

script:
  - prove -j$JOBS -r t/
